# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grayscale
description: > # this means to ignore newlines until "baseurl:"
  Grayscale was founded in 2017 with the aim of bringing together the most exciting contemporary music and visual art in a series of one-off events in interesting spaces around Dublin. Each unique event fosters collaborations between artists from these different disciplines, and allows them to present their work to the very highest standard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grayscale.ie" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
